server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: pet
    password: pet
    url: jdbc:mariadb://localhost:3306/petdb?serverTimezone=Asia/Seoul
    
  jpa:
    open-in-view: true #true - LAZY로딩 ok/ false - LAZY로딩 no
    hibernate:     
      ddl-auto: create  # create, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true       
          
  mail: # gmail smtp 설정
    host: smtp.gmail.com
    port: 587
    username: hyopin258@gmail.com
    password: dd13486900!00!
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true  
   
   
   
      
